/**
 * Created by vnguyen on 9/1/16.
 */
export const LOAD_TWEETS_BY_USER = 'LOAD_TWEETS_BY_USER';
export const LOAD_TWEETS_BY_USER_FAILURE = 'LOAD_TWEETS_BY_USER_FAILURE';
export const LOAD_TWEETS_BY_USER_SUCCESS = 'LOAD_TWEETS_BY_USER_SUCCESS';